# Service Config
server:
  port: 8081
  servlet:
    context-path: /api

# DataSource Config
spring:
  profiles:
    active: dev

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
